simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import simbion_core.urls as core

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include((core, 'simbion_core'), namespace='core')),
]

simbion_core/urls.py
from django.conf.urls import url
from .views import index, simbion_register, simbion_login, simbion_listbeasiswa,simbion_detailbeasiswa, simbion_detailbeasiswamahasiswa, simbion_formdaftarmahasiwa, simbion_listpendaftar
from .views import simbion_buatbeasiswa, simbion_beasiswadonatur, base_homepage_donatur, base_homepage_mahasiswa
from .views import simbion_beasiswadaripaket, simbion_paketbeasiswabaru, simbion_home, simbion_logout
from .views import register_mahasiswa, register_individual, register_yayasan, login


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register', simbion_register, name='simbion_register'),
    url(r'^login', login, name='login'),
    url(r'^submit-login', simbion_login, name='simbion_login'),
    url(r'^logout', simbion_logout, name='simbion_logout'),
    url(r'^list-beasiswa', simbion_listbeasiswa, name='simbion_listbeasiswa'),
    url(r'^detail-beasiswa', simbion_detailbeasiswa, name='simbion_detailbeasiswa'),
    url(r'^daftar-beasiswa', simbion_detailbeasiswamahasiswa, name='simbion_detailbeasiswamahasiswa'),
    url(r'^form-pendaftaran-beasiswa', simbion_formdaftarmahasiwa, name='simbion_formdaftarmahasiswa'),
    url(r'^beasiswa-paket', simbion_beasiswadaripaket, name='simbion_beasiswadaripaket'),
    url(r'^beasiswa-baru', simbion_paketbeasiswabaru, name='simbion_paketbeasiswabaru'),
    url(r'^buat-beasiswa', simbion_buatbeasiswa, name='simbion_buatbeasiswa'),
    url(r'^beasiswa-donatur', simbion_beasiswadonatur, name='simbion_beasiswadonatur'),
    url(r'^list-pendaftar', simbion_listpendaftar, name='simbion_listpendaftar'),
    url(r'^home', simbion_home, name='simbion_home'),
    url(r'^homepage-mahasiswa', base_homepage_mahasiswa, name='base_homepage_mahasiswa'),
    url(r'^homepage-donatur', base_homepage_donatur, name='base_homepage_donatur'),
    url(r'^mahasiswa', register_mahasiswa, name='register_mahasiswa'),
    url(r'^individual', register_individual, name='register_individual'),
    url(r'^yayasan', register_yayasan, name='register_yayasan'),
]

simbion_core/views.py
from django.shortcuts import render, redirect, reverse
from django.db import connection, transaction
from django.http.response import HttpResponseRedirect
from django.contrib import messages

# Create your views here.

response = {}
def index(request):
    return render(request, 'simbion_homepage.html')

def simbion_register(request):
    if ('username' in request.session.keys()):
        return HttpResponseRedirect(reverse('core:simbion_home'))
    return render(request, 'simbion_register.html')

def register_mahasiswa(request):
    if(request.method == "POST"):
        username = request.POST.get('username')
        password = request.POST.get('password')
        npm = request.POST.get('npm')
        email = request.POST.get('email')
        nama = request.POST.get('nama')
        notelp = request.POST.get('notelp')
        alamat_tinggal = request.POST.get('alamat_tinggal')
        alamat_domisili = request.POST.get('alamat_domisili')
        bank = request.POST.get('bank')
        no_rek = request.POST.get('no_rek')
        nama_pemilik = request.POST.get('nama_pemilik')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match) > 0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM mahasiswa WHERE npm = %s", [npm])
        match = cursor.fetchone();
        if(match):
            if len(match) > 0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'mahasiswa')"
        cursor.execute(query, [username, password])

        query = "INSERT INTO MAHASISWA(npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username) " \
                           "VALUES (%s, %s, %s, %s, %s, %s, %s, %s,%s, %s)"
        cursor.execute(query, [npm, email, nama, notelp, alamat_tinggal, alamat_domisili, bank, no_rek, nama_pemilik, username])

        request.session['username'] = username
        request.session['role'] = 'mahasiswa'

        return render(request, 'simbion_success_register.html')


def register_individual(request):
    if (request.method == "POST"):
        username = request.POST.get('usernameIn')
        password = request.POST.get('passwordIn')
        no_id = request.POST.get('no_idIn')
        nik = request.POST.get('nikIn')
        email = request.POST.get('emailIn')
        nama = request.POST.get('namaIn')
        npwp = request.POST.get('npwpIn')
        notelp = request.POST.get('notelpIn')
        alamat = request.POST.get('alamatIn')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM donatur WHERE nomor_identitas = %s", [no_id])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM individual_donor WHERE nik = %s", [nik])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'donatur')"
        cursor.execute(query, [username, password])


        query = "INSERT INTO donatur(nomor_identitas, email, nama, npwp, no_telp, alamat, username) " \
                         "VALUES (%s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_id, email, nama, npwp, notelp, alamat, username])


        query = "INSERT INTO INDIVIDUAL_DONOR(nik, nomor_identitas_donatur) VALUES (%s, %s)"
        cursor.execute(query, [nik, no_id])


        request.session['username'] = username
        request.session['role'] = 'donatur'

        return render(request, 'simbion_success_register.html')

def register_yayasan(request):
    if (request.method == "POST"):
        username = request.POST.get('usernameYa')
        password = request.POST.get('passwordYa')
        no_id = request.POST.get('no_idYa')
        no_sk = request.POST.get('no_skYa')
        email = request.POST.get('emailYa')
        nama = request.POST.get('namaYa')
        notelp = request.POST.get('notelpYa')
        npwp = request.POST.get('npwpYa')
        alamat = request.POST.get('alamatYa')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM donatur WHERE nomor_identitas = %s", [no_id])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM yayasan WHERE no_sk_yayasan = %s", [no_sk])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'donatur')"
        cursor.execute(query, [username, password])

        query = "INSERT INTO donatur(nomor_identitas, email, nama, npwp, no_telp, alamat, username) " \
                         "VALUES (%s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_id, email, nama, npwp, notelp, alamat, username])

        query = "INSERT INTO YAYASAN(no_sk_yayasan, email, nama, no_telp_cp, nomor_identitas_donatur) " \
                           "VALUES (%s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_sk, email, nama, notelp, no_id])

        request.session['username'] = username
        request.session['role'] = 'donatur'

        return render(request, 'simbion_success_register.html')


def simbion_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM pengguna WHERE username= %s", [username])
    match = cursor.fetchone();
    if (match):
        cursor.execute("SELECT password FROM pengguna WHERE username='" + username + "'")
        match = cursor.fetchone();
        if (match[0] == password):
            request.session['username'] = username
            cursor.execute("SELECT role FROM pengguna WHERE username='" + username + "'")
            match = cursor.fetchone();
            request.session['role'] = match[0]
            return HttpResponseRedirect(reverse('core:simbion_home'))
    messages.error(request, "Username atau Password yang anda masukkan salah")
    return HttpResponseRedirect(reverse('core:login'))

def simbion_home(request):
    if ('username' in request.session.keys()):
        role = request.session['role']
        if (role != "mahasiswa"):
            return render(request, 'layout/base_homepage_donatur.html')
        return render(request, 'layout/base_homepage_mahasiswa.html')
    else:
        return HttpResponseRedirect(reverse('core:simbion_login'))

def login(request):
    if ('username' in request.session.keys()):
        return HttpResponseRedirect(reverse('core:simbion_home'))
    return render(request, 'simbion_login.html')

def simbion_logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('core:index'))

def simbion_listbeasiswa(request):
    return render(request, 'simbion_success_daftar.html')

def simbion_listpendaftar(request):
    cursor = connection.cursor()
    response['username'] = request.session['username']

    cursor.execute(" SELECT distinct nama, deskripsi, kode FROM skema_beasiswa")
    response['detail_beasiswa'] = cursor.fetchone()

    cursor.execute("SELECT no_urut, nama, npm, waktu_daftar, status_terima FROM pendaftaran NATURAL JOIN mahasiswa")
    response['array_pendaftar'] = cursor.fetchall()

    return render(request, 'simbion_listpendaftar.html', response)

def simbion_listpendaftar_terima(request, no_urut, kode_beasiswa, npm):
    cursor = connection.cursor()
    cursor.execute("UPDATE pendaftaran SET status_terima='DITERIMA' WHERE no_urut='" + no_urut + "' AND kode_skema_beasiswa='" + kode_beasiswa + "' AND npm='" + npm + "'")

    return detail(request, kode_beasiswa)

def simbion_listpendaftar_tolak(request, no_urut, kode_beasiswa, npm):
    cursor = connection.cursor()
    cursor.execute("UPDATE pendaftaran SET status_terima='DITOLAK' WHERE no_urut='" + no_urut + "' AND kode_skema_beasiswa='" + kode_beasiswa + "' AND npm='" + npm + "'")

    return detail(request, kode_beasiswa)

def simbion_detailbeasiswa(request):
    return render(request, 'simbion_detailbeasiswa.html')

def simbion_detailbeasiswamahasiswa(request):
    return render(request, 'simbion_detailbeasiswamahasiswa.html')

def simbion_formdaftarmahasiwa(request):
    cursor = connection.cursor()

    cursor.execute("SELECT kode, nama, tgl_mulai_pendaftaran from skema_beasiswa_aktif JOIN skema_beasiswa ON kode_skema_beasiswa = kode WHERE status = 'TRUE' ORDER BY kode")
    response['array_beasiswa_aktif'] = cursor.fetchall()

    return render(request, 'simbion_formdaftarmahasiswa.html', response)

def simbion_buatbeasiswa(request):
    return render(request, 'simbion_buatbeasiswa.html')

def simbion_beasiswadonatur(request):
    cursor = connection.cursor()
    response['username'] = request.session['username']

simbion_core/templates/simbion_beasiswadaripaket.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../../../theme3.css"> </head>

<body>{% extends "layout/base_donatur.html" %} {% load static %} {% block content %}
<div class="py-5 filter-gradient" style="background-image: url('https://content.cdntwrk.com/mediaproxy?url=https%3A%2F%2Fatmedia.imgix.net%2F4d58e062e66cfb64196d9acc58342300eaefb9fa%3Fw%3D1500%26fit%3Dmax&size=1&version=1522439771&sig=530fd8ea4703ba4246e560a523fde5a4&default=hubs%2Ftilebg-blogs.jpg');">
  <div class="container">
    <div class="row">
      <div class="align-self-center col-md-6 text-white">
        <h1 class="text-center text-md-left display-3 text-light">Tambah
          <br>Beasiswa Baru dari Paket</h1>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-body p-5">
            <h3 class="pb-3">Menambah Beasiswa Baru</h3>
            <form action="{% url 'simbion_core:simbion_beasiswadaripaket' %}">
              <div class="form-group">
                <label class="text-light">Kode Beasiswa</label>
                <input type="text" class="form-control" id="kode" name="kode" required> </div>
              <div class="form-group">
                <label class="text-light">Nomor Urut</label>
                <input type="text" class="form-control" id="nomor" name="nomor" required> </div>
              <div class="form-group">
                <label class="text-light">Tanggal Mulai Pendaftaran</label>
                <input type="text" class="form-control" id="tgl_mulai" name="tgl_mulai" required> </div>
              <div class="form-group">
                <label class="text-light">Tanggal Tutup Pendaftaran</label>
                <input type="text" class="form-control" id="tgl_tutup" name="tgl_tutup" required> </div>
              <br>
              <a class="btn text-center btn-block btn-lg py-1 justify-content-center align-items-center align-self-center btn-info" href="#" data-toggle="modal">Submit</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

</html>
{% endblock %}

simbion_core/templates/simbion_beasiswadonatur.html
{% extends "layout/base_donatur.html" %}

{% load static %}

{% block content %}

<div class="py-5 filter-dark" style="background-image: url(&quot;https://preview.ibb.co/bwY6B7/laptop.jpg&quot;); background-size: auto; background-repeat: repeat;">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="display-4 text-info">
            <b>LIST BEASISWA</b>
          </h3>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 bg-info">
    <div class="container">
      <div class="row my-3">
        <div class="col-md-3">
          <div class="card bg-light">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">NO URUT SKEMA BEASISWA</span> 2 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">KODE SKEMA</span> 20172018 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">WAKTU PENUTUPAN</span> 31 Agustus 2018 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">STATUS</span> Dibuka</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">JUMLAH PENDAFTAR</span> 10</li>
            </ul>
            <div class="card-body">
              <p align="center">
              <a href="{% url 'core:simbion_listpendaftar' %}" class="btn btn-primary">PILIH</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card bg-light">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-center text-light">
                <span class="badge badge-pill w-100 badge-secondary">NO URUT SKEMA BEASISWA</span> 1 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">KODE SKEMA</span> 20172018 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">WAKTU PENUTUPAN</span> 31 April 2018 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">STATUS</span> Ditutup </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">JUMLAH PENDAFTAR</span> 15 </li>
            </ul>
            <div class="card-body">
              <p align="center">
                <a href="{% url 'core:simbion_listpendaftar' %}" class="btn btn-primary">PILIH</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card bg-light">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">NO URUT SKEMA BEASISWA</span> 3 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">KODE SKEMA</span> 20182019</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">WAKTU PENUTUPAN</span> 31 Juli 2019</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">STATUS</span> Dibuka</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">JUMLAH PENDAFTAR</span> 5 </li>
            </ul>
            <div class="card-body">
              <p align="center">
              <a href="{% url 'core:simbion_listpendaftar' %}" class="btn btn-primary">PILIH</a>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card bg-light">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">NO URUT SKEMA BEASISWA</span> 4 </li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">KODE SKEMA</span> 20182019</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">WAKTU PENUTUPAN</span> 31 Agustus 2019</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">STATUS</span> Dibuka</li>
              <li class="list-group-item text-center">
                <span class="badge badge-pill w-100 badge-secondary">JUMLAH PENDAFTAR</span> 25</li>
            </ul>
            <div class="card-body">
              <p align="center">
              <a href="{% url 'core:simbion_listpendaftar' %}" class="btn btn-primary">PILIH</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="bg-info">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="pagination justify-content-center">
            <li class="page-item">
              <a class="page-link" href="#">
                <span>«</span>
                <span class="sr-only">Previous</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">1</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">4</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#">
                <span>»</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

simbion_core/templates/simbion_buatbeasiswa.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../../../theme3.css"> </head>

<body>{% extends "layout/base_donatur.html" %} {% load static %} {% block content %}
  <div class="py-5 filter-dark" style="background-image: url('https://content.cdntwrk.com/mediaproxy?url=https%3A%2F%2Fatmedia.imgix.net%2F4d58e062e66cfb64196d9acc58342300eaefb9fa%3Fw%3D1500%26fit%3Dmax&size=1&version=1522439771&sig=530fd8ea4703ba4246e560a523fde5a4&default=hubs%2Ftilebg-blogs.jpg');background-repeat:repeat-x;background-position:center top;background-size:fit;">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Membuat Beasiswa Baru</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="m-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <hr class="bg-info"> </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div class="align-self-center col-md-6 p-1">
          <div class="card">
            <div class="card-block p-5 bg-light" style="background-image: url('-');">
              <hr class="bg-info">
              <br>
              <a href="{% url 'simbion_core:simbion_paketbeasiswabaru' %}" class="btn w-100 py-4 btn-lg btn-info">Membuat Paket Beasiswa Baru</a>
              <br>
              <br>
              <hr class="bg-info"> </div>
          </div>
        </div>
        <div class="align-self-center col-md-6 p-1">
          <div class="card">
            <div class="p-5 border-light bg-light">
              <hr class="bg-info">
              <br>
              <a href="{% url 'simbion_core:simbion_beasiswadaripaket' %}" class="btn w-100 py-4 btn-lg btn-info">Menambahkan Beasiswa dari Paket</a>
              <br>
              <br>
              <hr class="bg-info"> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <hr class="bg-info"> </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br> {% endblock %}
</body>

</html>

simbion_core/templates/simbion_detailbeasiswa.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../../../theme3.css"> </head>


<body>{% extends "layout/base_detailbeasiswa.html" %}{% load static %} {% block content %}
  <div class="py-5 bg-secondary filter-dark" style="background-image: url('https://content.cdntwrk.com/mediaproxy?url=https%3A%2F%2Fatmedia.imgix.net%2F4d58e062e66cfb64196d9acc58342300eaefb9fa%3Fw%3D1500%26fit%3Dmax&size=1&version=1522439771&sig=530fd8ea4703ba4246e560a523fde5a4&default=hubs%2Ftilebg-blogs.jpg');">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Informasi Beasiswa</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-5 bg-primary" style="background-image: url(&quot;-&quot;);">
    <div class="container">
      <div class="row">
        <div class="p-3 align-self-center col-md-12">
          <div class="card">
            <div class="card-block p-5 bg-secondary border border-light">
              <h2 class="text-light">[Nama Skema Beasiswa] - [Kode Skema Beasiswa]</h2>
              <br>
              <hr class="bg-light">
              <br>
              <h4 class="text-light">[Jenis Skema Beasiswa] dibuat oleh [nomor_identitas_donatur]
                <br>
                <br>[Ini adalah deskripsi, hanya terdiri dari 50 karakter saja.
                <br>Tidak usah banyak banyak, hanya menjelaskan beasiswa tersebut]
                <br>
                <br>Syarat Beasiswa : [syarat]</h4>
              <br>
              <hr class="bg-light">
              <br> </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

</html>
{% endblock %}

simbion_core/templates/simbion_detailbeasiswamahasiswa.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../../../theme3.css"> </head>

<body>{% extends "layout/base_mahasiswa.html" %} {% load static %} {% block content %}
  <div class="py-5 bg-secondary filter-dark" style="background-image: url('../../simbion/static/img/artikel-1-1-564x350.jpg');">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Informasi Beasiswa</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="p-5 bg-primary" style="background-image: url(&quot;-&quot;);">
    <div class="container">
      <div class="row">
        <div class="p-3 align-self-center col-md-12">
          <div class="card">
            <div class="card-block p-5 bg-secondary border border-light">
              <h2 class="text-light">[Nama Skema Beasiswa] - [Kode Skema Beasiswa]</h2>
              <br>
              <hr class="bg-light">
              <br>
              <h4 class="text-light">[Jenis Skema Beasiswa] dibuat oleh [nomor_identitas_donatur]
                <br>
                <br>[Ini adalah deskripsi, hanya terdiri dari 50 karakter saja.
                <br>Tidak usah banyak banyak, hanya menjelaskan beasiswa tersebut]
                <br>
                <br>Syarat Beasiswa : [syarat]</h4>
              <br>
              <hr class="bg-light">
              <br>
              <p align="center">
              <a href="{% url 'core:simbion_formdaftarmahasiswa' %}" class="btn btn-lg btn-info border border-light">Daftar Beasiswa Ini</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br> {% endblock %}
</body>

</html>

simbion_core/templates/simbion_formdaftarmahasiswa.html
{% extends "layout/base_mahasiswa.html" %}

{% load static %}

{% block content %}

<div class="py-5 filter-dark" style="background-image: url(&quot;https://preview.ibb.co/bwY6B7/laptop.jpg&quot;); background-size: auto; background-repeat: repeat; background-position: left top;" class="py-5 filter-light w-100 h-25">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h3 class="display-4 text-secondary text-center">
            <b>DAFTAR BEASISWA</b>
          </h3>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 text-secondary bg-primary">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-white bg-info">
          <h1>Form Pendaftaran Beasiswa</h1>
          <p>Masukkan data diri anda</p>
          <form>
            <div class="form-group">
              <label for="InputEmail1">Kode Beasiswa</label>
              <select class="form-control">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </div>
            <div class="form-group">
              <label for="InputName">NPM</label>
              <input type="text" class="form-control" id="InputName" placeholder="Your NPM"> </div>
            <div class="form-group">
              <label for="InputEmail1">Email</label>
              <input type="email" class="form-control" id="InputEmail1" placeholder="Your email"> </div>
            <div class="form-group">
              <label for="InputEmail1">Indeks Prestasi Semester (IPS)</label>
              <input type="text" class="form-control" id="inlineFormInput" placeholder="Your IP"> </div>
            <p align="center">
            <button type="submit" class="btn btn-secondary">Submit</button>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}