simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import simbion_core.urls as core

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include((core, 'simbion_core'), namespace='core')),
]

simbion_core/urls.py
from django.conf.urls import url
from .views import index, simbion_register, simbion_login, simbion_listbeasiswa,simbion_detailbeasiswa, simbion_detailbeasiswamahasiswa, simbion_formdaftarmahasiwa, simbion_listpendaftar
from .views import simbion_buatbeasiswa, simbion_beasiswadonatur, base_homepage_donatur, base_homepage_mahasiswa
from .views import simbion_beasiswadaripaket, simbion_paketbeasiswabaru, simbion_home, simbion_logout
from .views import register_mahasiswa, register_individual, register_yayasan, login


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register', simbion_register, name='simbion_register'),
    url(r'^login', login, name='login'),
    url(r'^submit-login', simbion_login, name='simbion_login'),
    url(r'^logout', simbion_logout, name='simbion_logout'),
    url(r'^list-beasiswa', simbion_listbeasiswa, name='simbion_listbeasiswa'),
    url(r'^detail-beasiswa', simbion_detailbeasiswa, name='simbion_detailbeasiswa'),
    url(r'^daftar-beasiswa', simbion_detailbeasiswamahasiswa, name='simbion_detailbeasiswamahasiswa'),
    url(r'^form-pendaftaran-beasiswa', simbion_formdaftarmahasiwa, name='simbion_formdaftarmahasiswa'),
    url(r'^beasiswa-paket', simbion_beasiswadaripaket, name='simbion_beasiswadaripaket'),
    url(r'^beasiswa-baru', simbion_paketbeasiswabaru, name='simbion_paketbeasiswabaru'),
    url(r'^buat-beasiswa', simbion_buatbeasiswa, name='simbion_buatbeasiswa'),
    url(r'^beasiswa-donatur', simbion_beasiswadonatur, name='simbion_beasiswadonatur'),
    url(r'^list-pendaftar', simbion_listpendaftar, name='simbion_listpendaftar'),
    url(r'^home', simbion_home, name='simbion_home'),
    url(r'^homepage-mahasiswa', base_homepage_mahasiswa, name='base_homepage_mahasiswa'),
    url(r'^homepage-donatur', base_homepage_donatur, name='base_homepage_donatur'),
    url(r'^mahasiswa', register_mahasiswa, name='register_mahasiswa'),
    url(r'^individual', register_individual, name='register_individual'),
    url(r'^yayasan', register_yayasan, name='register_yayasan'),
]

simbion_core/views.py
from django.shortcuts import render, redirect, reverse
from django.db import connection, transaction
from django.http.response import HttpResponseRedirect
from django.contrib import messages

# Create your views here.

response = {}
def index(request):
    return render(request, 'simbion_homepage.html')

def simbion_register(request):
    if ('username' in request.session.keys()):
        return HttpResponseRedirect(reverse('core:simbion_home'))
    return render(request, 'simbion_register.html')

def register_mahasiswa(request):
    if(request.method == "POST"):
        username = request.POST.get('username')
        password = request.POST.get('password')
        npm = request.POST.get('npm')
        email = request.POST.get('email')
        nama = request.POST.get('nama')
        notelp = request.POST.get('notelp')
        alamat_tinggal = request.POST.get('alamat_tinggal')
        alamat_domisili = request.POST.get('alamat_domisili')
        bank = request.POST.get('bank')
        no_rek = request.POST.get('no_rek')
        nama_pemilik = request.POST.get('nama_pemilik')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match) > 0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM mahasiswa WHERE npm = %s", [npm])
        match = cursor.fetchone();
        if(match):
            if len(match) > 0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'mahasiswa')"
        cursor.execute(query, [username, password])

        query = "INSERT INTO MAHASISWA(npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username) " \
                           "VALUES (%s, %s, %s, %s, %s, %s, %s, %s,%s, %s)"
        cursor.execute(query, [npm, email, nama, notelp, alamat_tinggal, alamat_domisili, bank, no_rek, nama_pemilik, username])

        request.session['username'] = username
        request.session['role'] = 'mahasiswa'

        return render(request, 'simbion_success_register.html')


def register_individual(request):
    if (request.method == "POST"):
        username = request.POST.get('usernameIn')
        password = request.POST.get('passwordIn')
        no_id = request.POST.get('no_idIn')
        nik = request.POST.get('nikIn')
        email = request.POST.get('emailIn')
        nama = request.POST.get('namaIn')
        npwp = request.POST.get('npwpIn')
        notelp = request.POST.get('notelpIn')
        alamat = request.POST.get('alamatIn')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM donatur WHERE nomor_identitas = %s", [no_id])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM individual_donor WHERE nik = %s", [nik])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'donatur')"
        cursor.execute(query, [username, password])


        query = "INSERT INTO donatur(nomor_identitas, email, nama, npwp, no_telp, alamat, username) " \
                         "VALUES (%s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_id, email, nama, npwp, notelp, alamat, username])


        query = "INSERT INTO INDIVIDUAL_DONOR(nik, nomor_identitas_donatur) VALUES (%s, %s)"
        cursor.execute(query, [nik, no_id])


        request.session['username'] = username
        request.session['role'] = 'donatur'

        return render(request, 'simbion_success_register.html')

def register_yayasan(request):
    if (request.method == "POST"):
        username = request.POST.get('usernameYa')
        password = request.POST.get('passwordYa')
        no_id = request.POST.get('no_idYa')
        no_sk = request.POST.get('no_skYa')
        email = request.POST.get('emailYa')
        nama = request.POST.get('namaYa')
        notelp = request.POST.get('notelpYa')
        npwp = request.POST.get('npwpYa')
        alamat = request.POST.get('alamatYa')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM pengguna WHERE username = %s", [username])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM donatur WHERE nomor_identitas = %s", [no_id])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        cursor = connection.cursor()
        cursor.execute("SELECT * FROM yayasan WHERE no_sk_yayasan = %s", [no_sk])
        match = cursor.fetchone();
        if(match):
            if len(match)>0:
                return render(request, 'simbion_fail_register.html')

        query = "INSERT INTO PENGGUNA(username, password, role) VALUES (%s, %s, 'donatur')"
        cursor.execute(query, [username, password])

        query = "INSERT INTO donatur(nomor_identitas, email, nama, npwp, no_telp, alamat, username) " \
                         "VALUES (%s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_id, email, nama, npwp, notelp, alamat, username])

        query = "INSERT INTO YAYASAN(no_sk_yayasan, email, nama, no_telp_cp, nomor_identitas_donatur) " \
                           "VALUES (%s, %s, %s, %s, %s, %s)"
        cursor.execute(query, [no_sk, email, nama, notelp, no_id])

        request.session['username'] = username
        request.session['role'] = 'donatur'

        return render(request, 'simbion_success_register.html')


def simbion_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM pengguna WHERE username= %s", [username])
    match = cursor.fetchone();
    if (match):
        cursor.execute("SELECT password FROM pengguna WHERE username='" + username + "'")
        match = cursor.fetchone();
        if (match[0] == password):
            request.session['username'] = username
            cursor.execute("SELECT role FROM pengguna WHERE username='" + username + "'")
            match = cursor.fetchone();
            request.session['role'] = match[0]
            return HttpResponseRedirect(reverse('core:simbion_home'))
    messages.error(request, "Username atau Password yang anda masukkan salah")
    return HttpResponseRedirect(reverse('core:login'))

def simbion_home(request):
    if ('username' in request.session.keys()):
        role = request.session['role']
        if (role != "mahasiswa"):
            return render(request, 'layout/base_homepage_donatur.html')
        return render(request, 'layout/base_homepage_mahasiswa.html')
    else:
        return HttpResponseRedirect(reverse('core:simbion_login'))

def login(request):
    if ('username' in request.session.keys()):
        return HttpResponseRedirect(reverse('core:simbion_home'))
    return render(request, 'simbion_login.html')

def simbion_logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('core:index'))

def simbion_listbeasiswa(request):
    return render(request, 'simbion_success_daftar.html')

def simbion_listpendaftar(request):
    cursor = connection.cursor()
    response['username'] = request.session['username']

    cursor.execute(" SELECT distinct nama, deskripsi, kode FROM skema_beasiswa")
    response['detail_beasiswa'] = cursor.fetchone()

    cursor.execute("SELECT no_urut, nama, npm, waktu_daftar, status_terima FROM pendaftaran NATURAL JOIN mahasiswa")
    response['array_pendaftar'] = cursor.fetchall()

    return render(request, 'simbion_listpendaftar.html', response)

def simbion_listpendaftar_terima(request, no_urut, kode_beasiswa, npm):
    cursor = connection.cursor()
    cursor.execute("UPDATE pendaftaran SET status_terima='DITERIMA' WHERE no_urut='" + no_urut + "' AND kode_skema_beasiswa='" + kode_beasiswa + "' AND npm='" + npm + "'")

    return detail(request, kode_beasiswa)

def simbion_listpendaftar_tolak(request, no_urut, kode_beasiswa, npm):
    cursor = connection.cursor()
    cursor.execute("UPDATE pendaftaran SET status_terima='DITOLAK' WHERE no_urut='" + no_urut + "' AND kode_skema_beasiswa='" + kode_beasiswa + "' AND npm='" + npm + "'")

    return detail(request, kode_beasiswa)

def simbion_detailbeasiswa(request):
    return render(request, 'simbion_detailbeasiswa.html')

def simbion_detailbeasiswamahasiswa(request):
    return render(request, 'simbion_detailbeasiswamahasiswa.html')

def simbion_formdaftarmahasiwa(request):
    cursor = connection.cursor()

    cursor.execute("SELECT kode, nama, tgl_mulai_pendaftaran from skema_beasiswa_aktif JOIN skema_beasiswa ON kode_skema_beasiswa = kode WHERE status = 'TRUE' ORDER BY kode")
    response['array_beasiswa_aktif'] = cursor.fetchall()

    return render(request, 'simbion_formdaftarmahasiswa.html', response)

def simbion_buatbeasiswa(request):
    return render(request, 'simbion_buatbeasiswa.html')

def simbion_beasiswadonatur(request):
    cursor = connection.cursor()
    response['username'] = request.session['username']

simbion_core/templates/partials/footer.html
  <div class="text-white bg-light" id="footer">
    <div class="container">
      <div class="row">
        <div class="p-4 col-md-6">
          <h3 class="display-1 text-secondary">SIMBION</h3>
        </div>
        <div class="p-4 col-md-6">
          <h2 class="mb-4 text-secondary">Kontak kami</h2>
          <p>
            <a href="tel:+246 - 542 550 5462" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-phone"></i>+246 - 542 550 5462</a>
          </p>
          <p>
            <a href="mailto:info@pingendo.com" class="text-white">
              <i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@simbion.com</a>
          </p>
          <p>
            <a href="https://goo.gl/maps/AUq7b9W7yYJ2" class="text-white" target="_blank">
              <i class="fa d-inline mr-3 fa-map-marker text-secondary"></i>2016 Pacil</a>
          </p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 mt-3">
          <p class="text-center text-white">© Copyright 2018 Kelompok 12 - All rights reserved. </p>
        </div>
      </div>
    </div>
  </div>

simbion_core/templates/partials/header_donatur.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-light">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand">SIMBION</a>
      <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
        <ul class="navbar-nav text-info">
            <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'core:simbion_beasiswadonatur' %}">Lihat Beasiswa Anda</a>
          </li>
            <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'core:simbion_buatbeasiswa' %}">Membuat Beasiswa Baru</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'core:base_homepage_donatur' %}">List Beasiswa</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#definisi">Informasi</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#footer">Kontak Kami</a>
          </li>
        </ul>
        <a class="btn navbar-btn mx-2 btn-outline-secondary text-info" href="{% url 'core:simbion_logout' %}">Logout</a>
      </div>
    </div>
  </nav>

simbion_core/templates/partials/header_mahasiswa.html
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../../../../theme3.css"> </head>

<body>
  <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-light">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand">SIMBION</a>
      <div class="collapse navbar-collapse justify-content-center" id="navbar2SupportedContent">
        <ul class="navbar-nav text-info">
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'core:simbion_formdaftarmahasiswa' %}">Daftar Beasiswa</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="{% url 'core:base_homepage_mahasiswa' %}">List Beasiswa</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#definisi">Informasi</a>
          </li>
          <li class="nav-item mx-2">
            <a class="nav-link" href="#footer">Kontak Kami</a>
          </li>
        </ul>
        <a class="btn navbar-btn mx-2 btn-outline-secondary text-info" href="{% url 'core:simbion_logout' %}">Logout</a>
      </div>
    </div>
  </nav>
</body>

</html>